[general]
import = ["~/.config/alacritty/colors.yml"]

[window.padding]
x = 20
y = 20

[window]
opacity = 0.75
blur = true

[font.normal]
family = "CommitMono Nerd Font Mono"

[font]
size = 15.0

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
